name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/*.yml'
      - '**/*.py'
      - 'requirements.txt'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/*.yml'
      - '**/*.py'
      - 'requirements.txt'

permissions:
  actions: read
  contents: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  unit-test:
    name: Run unit test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install PIP dependencies
      run: python3 -m pip install -r requirements.txt
    - name: Run PyTest
      run: pytest --junit-xml=pytest.xml $(find test -name '*.py')
      env:
        PYTHONPATH: ${{ github.workspace }}
    - name: Publish Test Results
      if: ${{ always() }}
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: "**/*.xml"
        annotate_only: ${{ github.event_name == 'pull_request' }}
